spring:
  thymeleaf:
    prefix: classpath:/static/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/expressage
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
server:  port: 8081