spring:
  thymeleaf:
    prefix: classpath:/static/
    check-template-location: true
    cache: false
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    servlet:
      content-type: text/html
  datasource:
    url: jdbc:mysql://localhost:3306/expressage?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8&useSSL=false
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: localhost
    port: 6379
    pool:
      jedis:
        max-idle: 8
        min-idle: 0
        max-active: 8
        max-wait: -1
    timeout: 0
server:
  port: 8081
mybatis:
  type-aliases-package: com.expressage.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    auto-mapping-behavior: full